require("core.set")
require("core.remap")

require("plugins.alpha").config()
require("plugins.bufferline").config()
require("plugins.codeium").config()
require("plugins.commentary").config()
--require('plugins.dap').config();
require("plugins.formatter").config()
require("plugins.fugitive").config()
require("plugins.gitsigns").config()
require("plugins.harpoon").config()
require("plugins.hexokinase").config()
require("plugins.lsp")
require("plugins.lualine").config()
require("plugins.markdown").toc.config()
require("plugins.nvim-tree").config()
require("plugins.telescope").config()
-- require("plugins.theme").config()
require("plugins.treesitter").config()
require("plugins.trouble").config()
require("plugins.whichkey").config()
require("plugins.sniprun").config()
