clients:
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
    models:
      - name: llama3.1:8b
        max_input_tokens: 128000
        supports_function_calling: true
