pragma ComponentBehavior: Bound

import "../../config"
import "../../services"
import "../shared"
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Quickshell
import Quickshell.Io
import Quickshell.Services.Mpris

// Slide-out menu content
Rectangle {
    id: root

    property bool open: false
    signal closeRequested

    // Keyboard navigation
    property int selectedButtonIndex: -1
    readonly property int buttonCount: 7  // monitor1, monitor2, power, restart, logout, suspend, lock

    // Monitor status tracking
    property bool monitor1On: false
    property bool monitor2On: false

    focus: true

    Keys.onPressed: event => {
        if (!root.open)
            return;

        if (event.key === Qt.Key_Escape) {
            root.closeRequested();
            event.accepted = true;
        } else if (event.key === Qt.Key_Left) {
            if (selectedButtonIndex < 0) {
                // First press: start from rightmost
                selectedButtonIndex = buttonCount - 1;
            } else {
                // Navigate left (decrease index)
                selectedButtonIndex = Math.max(0, selectedButtonIndex - 1);
            }
            event.accepted = true;
        } else if (event.key === Qt.Key_Right) {
            if (selectedButtonIndex < 0) {
                // First press: start from leftmost
                selectedButtonIndex = 0;
            } else {
                // Navigate right (increase index)
                selectedButtonIndex = Math.min(buttonCount - 1, selectedButtonIndex + 1);
            }
            event.accepted = true;
        } else if (event.key === Qt.Key_Return || event.key === Qt.Key_Enter) {
            if (selectedButtonIndex >= 0) {
                // Trigger the selected button action
                root.closeRequested();
                if (selectedButtonIndex === 0) {
                    monitor1ToggleProcess.running = true;
                } else if (selectedButtonIndex === 1) {
                    monitor2ToggleProcess.running = true;
                } else if (selectedButtonIndex === 2) {
                    powerProcess.running = true;
                } else if (selectedButtonIndex === 3) {
                    restartProcess.running = true;
                } else if (selectedButtonIndex === 4) {
                    logoutProcess.running = true;
                } else if (selectedButtonIndex === 5) {
                    suspendProcess.running = true;
                } else if (selectedButtonIndex === 6) {
                    lockTimer.start();
                }
                event.accepted = true;
            }
        }
    }

    // Focus when menu opens
    onOpenChanged: {
        if (open) {
            root.forceActiveFocus();
            selectedButtonIndex = -1; // Reset selection
            calendar.currentDate = new Date(); // Reset to current month
            monitorCheckProcess.running = true; // Check monitor status
        }
    }

    // Get lock command from monitor config (generated by Nix)
    readonly property string lockCommand: NixConfig.lockCommand

    // Timer to delay lock command so menu can close
    Timer {
        id: lockTimer
        interval: 200
        onTriggered: lockProcess.running = true
    }

    // Process runners for each action
    Process {
        id: lockProcess
        command: ["sh", "-c", root.lockCommand]
    }

    Process {
        id: logoutProcess
        command: ["hyprctl", "dispatch", "exit"]
    }

    Process {
        id: suspendProcess
        command: ["systemctl", "suspend"]
    }

    Process {
        id: restartProcess
        command: ["systemctl", "reboot"]
    }

    Process {
        id: powerProcess
        command: ["systemctl", "poweroff"]
    }

    // Monitor status check process
    Process {
        id: monitorCheckProcess
        command: ["hyprctl", "monitors"]
        stdout: StdioCollector {
            onStreamFinished: {
                // Check if monitors are in the output
                root.monitor1On = text.includes("Monitor " + NixConfig.monitor1Name);
                root.monitor2On = text.includes("Monitor " + NixConfig.monitor2Name);
            }
        }
    }

    // Monitor toggle processes
    Process {
        id: monitor1ToggleProcess
        command: ["sh", "/home/nick/.config/dots/files/config/hypr/scripts/toggle_monitor.sh", "1"]
        onExited: {
            // Refresh monitor status after toggle
            monitorCheckTimer.start();
        }
    }

    Process {
        id: monitor2ToggleProcess
        command: ["sh", "/home/nick/.config/dots/files/config/hypr/scripts/toggle_monitor.sh", "2"]
        onExited: {
            // Refresh monitor status after toggle
            monitorCheckTimer.start();
        }
    }

    // Timer to refresh monitor status after toggle
    Timer {
        id: monitorCheckTimer
        interval: 500
        onTriggered: monitorCheckProcess.running = true
    }

    // Timer to periodically check monitor status
    Timer {
        running: root.open
        interval: 5000
        repeat: true
        onTriggered: monitorCheckProcess.running = true
    }

    width: Math.max(buttonRow.width, monitorRow.width, calendar.width) + Appearance.padding.large * 2
    height: contentColumn.height + Appearance.padding.large * 2
    radius: Appearance.rounding.normal
    // Square corners on right side, rounded on left
    topRightRadius: 0
    bottomRightRadius: 0
    color: NixConfig.layer(NixConfig.background, 0)
    border.width: 0

    // No animation - instant appearance
    opacity: 1
    scale: 1

    // ResourceBar component definition
    component ResourceBar: Row {
        id: resBar
        required property string label
        required property real value
        required property string rightText
        required property color barColor

        spacing: Appearance.spacing.small

        // Label
        Text {
            width: 22
            anchors.verticalCenter: parent.verticalCenter
            text: resBar.label
            font.family: Appearance.font.mono
            font.pixelSize: Appearance.font.normal
            font.bold: true
            color: resBar.barColor
            horizontalAlignment: Text.AlignLeft
        }

        // Bar container
        Rectangle {
            width: parent.width - 22 - 35 - Appearance.spacing.small * 2
            height: 6
            anchors.verticalCenter: parent.verticalCenter
            radius: Appearance.rounding.full
            color: Qt.alpha(NixConfig.textOnBackground, 0.1)

            // Fill bar
            Rectangle {
                width: parent.width * Math.max(0, Math.min(1, resBar.value))
                height: parent.height
                radius: parent.radius
                color: resBar.barColor

                Behavior on width {
                    NumberAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.OutCubic
                    }
                }
            }
        }

        // Right text (percentage or temp)
        Text {
            width: 35
            anchors.verticalCenter: parent.verticalCenter
            text: resBar.rightText
            font.family: Appearance.font.mono
            font.pixelSize: Appearance.font.smaller
            color: resBar.barColor
            horizontalAlignment: Text.AlignRight
        }
    }

    Column {
        id: contentColumn
        anchors.centerIn: parent
        spacing: Appearance.spacing.large

        // Calendar
        Rectangle {
            id: calendarContainer
            width: Math.max(buttonRow.width, 280)
            implicitHeight: calendar.implicitHeight + Appearance.padding.large * 2
            radius: Appearance.rounding.normal
            color: NixConfig.layer(NixConfig.surfaceContainer, 0)

            Column {
                id: calendar
                anchors.centerIn: parent
                width: parent.width - Appearance.padding.large * 2
                spacing: Appearance.spacing.normal

                property date currentDate: new Date()
                property int currMonth: currentDate.getMonth()
                property int currYear: currentDate.getFullYear()

                // Month navigation
                Row {
                    width: parent.width
                    spacing: Appearance.spacing.small

                    // Previous month button
                    Rectangle {
                        width: 30
                        height: 30
                        anchors.verticalCenter: parent.verticalCenter
                        radius: Appearance.rounding.full
                        color: prevMouseArea.containsMouse ? Qt.alpha(NixConfig.textOnBackground, 0.1) : "transparent"

                        Text {
                            anchors.centerIn: parent
                            text: ""
                            font.family: Appearance.font.mono
                            font.pixelSize: Appearance.font.large
                            font.bold: true
                            color: NixConfig.primary
                        }

                        MouseArea {
                            id: prevMouseArea
                            anchors.fill: parent
                            hoverEnabled: true
                            cursorShape: Qt.PointingHandCursor
                            onClicked: {
                                calendar.currentDate = new Date(calendar.currYear, calendar.currMonth - 1, 1);
                            }
                        }
                    }

                    // Month/Year display
                    Text {
                        width: parent.width - 60 - Appearance.spacing.small * 2
                        anchors.verticalCenter: parent.verticalCenter
                        horizontalAlignment: Text.AlignHCenter
                        text: Qt.formatDate(calendar.currentDate, "MMMM yyyy")
                        font.family: Appearance.font.mono
                        font.pixelSize: Appearance.font.larger
                        font.bold: true
                        font.capitalization: Font.Capitalize
                        color: NixConfig.primary
                    }

                    // Next month button
                    Rectangle {
                        width: 30
                        height: 30
                        anchors.verticalCenter: parent.verticalCenter
                        radius: Appearance.rounding.full
                        color: nextMouseArea.containsMouse ? Qt.alpha(NixConfig.textOnBackground, 0.1) : "transparent"

                        Text {
                            anchors.centerIn: parent
                            text: ""
                            font.family: Appearance.font.mono
                            font.pixelSize: Appearance.font.large
                            color: NixConfig.primary
                        }

                        MouseArea {
                            id: nextMouseArea
                            anchors.fill: parent
                            hoverEnabled: true
                            cursorShape: Qt.PointingHandCursor
                            onClicked: {
                                calendar.currentDate = new Date(calendar.currYear, calendar.currMonth + 1, 1);
                            }
                        }
                    }
                }

                // Day of week headers
                DayOfWeekRow {
                    width: parent.width
                    locale: Qt.locale()

                    delegate: Text {
                        required property var model
                        horizontalAlignment: Text.AlignHCenter
                        text: model.shortName
                        font.family: Appearance.font.mono
                        font.pixelSize: Appearance.font.smaller
                        color: NixConfig.textOnSurface
                        opacity: 0.7
                    }
                }

                // Calendar grid
                Item {
                    width: parent.width
                    implicitHeight: grid.implicitHeight

                    MonthGrid {
                        id: grid
                        anchors.fill: parent
                        month: calendar.currMonth
                        year: calendar.currYear
                        locale: Qt.locale()
                        spacing: 2

                        delegate: Rectangle {
                            required property var model

                            implicitWidth: 36
                            implicitHeight: 36
                            color: model.today ? NixConfig.primary : "transparent"
                            radius: Appearance.rounding.small

                            Text {
                                anchors.centerIn: parent
                                text: model.day
                                font.family: Appearance.font.mono
                                font.pixelSize: Appearance.font.normal
                                color: model.today ? NixConfig.textOnPrimary : (model.month === grid.month ? NixConfig.textOnSurface : NixConfig.textOnSurface)
                                opacity: model.month === grid.month ? 1 : 0.4
                            }
                        }
                    }
                }
            }
        }

        // Weather and Performance row
        Row {
            anchors.horizontalCenter: parent.horizontalCenter
            spacing: Appearance.spacing.large

            readonly property real targetWidth: Math.max(buttonRow.width, calendarContainer.width)

            // Weather section (40%)
            Rectangle {
                width: parent.targetWidth * 0.4 - Appearance.spacing.large * 0.6
                height: 120
                radius: Appearance.rounding.normal
                color: NixConfig.surfaceContainer

                Column {
                    anchors.centerIn: parent
                    spacing: Appearance.spacing.small

                    // Weather icon and temperature on same line
                    Row {
                        anchors.horizontalCenter: parent.horizontalCenter
                        spacing: Appearance.spacing.small

                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            text: Weather.weatherIcon
                            font.family: Appearance.font.mono
                            font.pixelSize: Appearance.font.large
                            color: NixConfig.primary
                        }

                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            text: Weather.temperature
                            font.family: Appearance.font.mono
                            font.pixelSize: Appearance.font.larger
                            font.bold: true
                            color: NixConfig.textOnSurface
                        }
                    }

                    Text {
                        anchors.horizontalCenter: parent.horizontalCenter
                        text: Weather.condition
                        font.family: Appearance.font.mono
                        font.pixelSize: Appearance.font.smaller
                        color: NixConfig.secondary
                        elide: Text.ElideRight
                        width: parent.parent.width - Appearance.padding.normal * 2
                        horizontalAlignment: Text.AlignHCenter
                    }
                }
            }

            // Performance stats (60%)
            Rectangle {
                width: parent.targetWidth * 0.6 - Appearance.spacing.large * 0.4
                height: 120
                radius: Appearance.rounding.normal
                color: NixConfig.surfaceContainer

                Column {
                    anchors.centerIn: parent
                    width: parent.width - Appearance.padding.normal * 2
                    spacing: Appearance.spacing.small

                    // CPU
                    ResourceBar {
                        width: parent.width
                        label: ""
                        value: SystemUsage.cpuPerc
                        rightText: `${Math.round(SystemUsage.cpuTemp)}°C`
                        barColor: NixConfig.primary
                    }

                    // GPU
                    ResourceBar {
                        width: parent.width
                        label: "󰢮"
                        value: SystemUsage.gpuPerc
                        rightText: SystemUsage.gpuType !== "NONE" ? `${Math.round(SystemUsage.gpuTemp)}°C` : "N/A"
                        barColor: NixConfig.tertiary
                    }

                    // RAM
                    ResourceBar {
                        width: parent.width
                        label: ""
                        value: SystemUsage.memPerc
                        rightText: `${Math.round(SystemUsage.memPerc * 100)}%`
                        barColor: NixConfig.quaternary
                    }

                    // Storage
                    ResourceBar {
                        width: parent.width
                        label: ""
                        value: SystemUsage.storagePerc
                        rightText: `${Math.round(SystemUsage.storagePerc * 100)}%`
                        barColor: NixConfig.quinary
                    }
                }
            }
        }

        // Now Playing widget
        Rectangle {
            id: mediaWidget
            width: Math.max(buttonRow.width, calendarContainer.width)
            height: 120
            radius: Appearance.rounding.normal
            color: NixConfig.surfaceContainer
            visible: activePlayer !== null

            // Select active player with priority: playing media > paused media > any player
            // Prioritize actual music players (spotify, vlc, etc) over browsers
            readonly property var activePlayer: {
                let players = Mpris.players.values;
                if (players.length === 0)
                    return null;

                // Browser identities to deprioritize
                let browsers = ["brave", "chrome", "chromium", "firefox", "edge"];

                // First, try to find a playing non-browser player
                let playingPlayer = players.find(p => {
                    let id = p.identity.toLowerCase();
                    return p.isPlaying && !browsers.some(b => id.includes(b));
                });
                if (playingPlayer)
                    return playingPlayer;

                // Then, try any playing player (including browsers)
                playingPlayer = players.find(p => p.isPlaying);
                if (playingPlayer)
                    return playingPlayer;

                // Then, try a paused non-browser player
                let pausedPlayer = players.find(p => {
                    let id = p.identity.toLowerCase();
                    return !browsers.some(b => id.includes(b));
                });
                if (pausedPlayer)
                    return pausedPlayer;

                // Finally, fall back to first player
                return players[0];
            }

            Row {
                anchors.fill: parent
                anchors.margins: Appearance.padding.normal
                spacing: Appearance.spacing.normal

                // Album art
                Rectangle {
                    width: 90
                    height: 90
                    anchors.verticalCenter: parent.verticalCenter
                    radius: Appearance.rounding.small
                    color: NixConfig.surface
                    clip: true

                    // Fallback icon
                    Text {
                        anchors.centerIn: parent
                        text: ""
                        font.family: Appearance.font.mono
                        font.pixelSize: 40
                        color: NixConfig.secondary
                        visible: !albumArt.visible
                    }

                    Image {
                        id: albumArt
                        anchors.fill: parent
                        source: mediaWidget.activePlayer?.trackArtUrl ?? ""
                        fillMode: Image.PreserveAspectCrop
                        visible: status === Image.Ready
                        smooth: true
                    }
                }

                // Track info and controls
                Column {
                    width: parent.width - 90 - parent.spacing
                    anchors.verticalCenter: parent.verticalCenter
                    spacing: Appearance.spacing.small

                    // Track title
                    Text {
                        width: parent.width
                        text: mediaWidget.activePlayer?.trackTitle || "No media"
                        font.family: Appearance.font.mono
                        font.pixelSize: Appearance.font.normal
                        font.bold: true
                        color: NixConfig.textOnSurface
                        elide: Text.ElideRight
                    }

                    // Artist
                    Text {
                        width: parent.width
                        text: mediaWidget.activePlayer?.trackArtist || "Unknown artist"
                        font.family: Appearance.font.mono
                        font.pixelSize: Appearance.font.smaller
                        color: NixConfig.secondary
                        elide: Text.ElideRight
                    }

                    // Album
                    Text {
                        width: parent.width
                        text: mediaWidget.activePlayer?.trackAlbum || ""
                        font.family: Appearance.font.mono
                        font.pixelSize: Appearance.font.smaller
                        color: NixConfig.secondary
                        elide: Text.ElideRight
                        visible: text !== ""
                    }

                    // Media controls
                    Row {
                        anchors.horizontalCenter: parent.horizontalCenter
                        spacing: Appearance.spacing.small

                        // Previous button
                        Rectangle {
                            width: 35
                            height: 35
                            radius: Appearance.rounding.full
                            color: mediaPrevMouseArea.containsMouse ? Qt.alpha(NixConfig.textOnBackground, 0.1) : "transparent"
                            visible: mediaWidget.activePlayer?.canGoPrevious ?? false

                            Text {
                                anchors.centerIn: parent
                                text: "󰒮"
                                font.family: Appearance.font.mono
                                font.pixelSize: Appearance.font.normal
                                color: NixConfig.primary
                            }

                            MouseArea {
                                id: mediaPrevMouseArea
                                anchors.fill: parent
                                hoverEnabled: true
                                cursorShape: Qt.PointingHandCursor
                                onClicked: mediaWidget.activePlayer?.previous()
                            }
                        }

                        // Play/Pause button
                        Rectangle {
                            width: 35
                            height: 35
                            radius: Appearance.rounding.full
                            color: mediaPlayMouseArea.containsMouse ? Qt.alpha(NixConfig.textOnBackground, 0.1) : "transparent"
                            visible: mediaWidget.activePlayer?.canTogglePlaying ?? false

                            Text {
                                anchors.centerIn: parent
                                text: (mediaWidget.activePlayer?.isPlaying ?? false) ? "󰏤" : "󰐊"
                                font.family: Appearance.font.mono
                                font.pixelSize: Appearance.font.normal
                                color: NixConfig.primary
                            }

                            MouseArea {
                                id: mediaPlayMouseArea
                                anchors.fill: parent
                                hoverEnabled: true
                                cursorShape: Qt.PointingHandCursor
                                onClicked: mediaWidget.activePlayer?.togglePlaying()
                            }
                        }

                        // Next button
                        Rectangle {
                            width: 35
                            height: 35
                            radius: Appearance.rounding.full
                            color: mediaNextMouseArea.containsMouse ? Qt.alpha(NixConfig.textOnBackground, 0.1) : "transparent"
                            visible: mediaWidget.activePlayer?.canGoNext ?? false

                            Text {
                                anchors.centerIn: parent
                                text: "󰒭"
                                font.family: Appearance.font.mono
                                font.pixelSize: Appearance.font.normal
                                color: NixConfig.primary
                            }

                            MouseArea {
                                id: mediaNextMouseArea
                                anchors.fill: parent
                                hoverEnabled: true
                                cursorShape: Qt.PointingHandCursor
                                onClicked: mediaWidget.activePlayer?.next()
                            }
                        }
                    }
                }
            }
        }

        // Monitor buttons row
        Row {
            id: monitorRow
            anchors.horizontalCenter: parent.horizontalCenter
            spacing: Appearance.spacing.normal

            // Monitor 1 button
            Rectangle {
                width: 50
                height: 50
                radius: Appearance.rounding.small
                color: root.selectedButtonIndex === 0 ? NixConfig.primary : NixConfig.surfaceContainer
                scale: monitor1MouseArea.containsMouse || root.selectedButtonIndex === 0 ? 1.1 : 1.0
                transformOrigin: Item.Center

                Behavior on color {
                    ColorAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.Linear
                    }
                }

                Behavior on scale {
                    NumberAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.OutBack
                    }
                }

                Text {
                    anchors.centerIn: parent
                    text: root.monitor1On ? "󰎤" : "󰎦"
                    font.family: Appearance.font.mono
                    font.pixelSize: Appearance.font.large
                    font.bold: true
                    color: root.selectedButtonIndex === 0 ? NixConfig.textOnPrimary : NixConfig.primary

                    Behavior on color {
                        ColorAnimation {
                            duration: Appearance.anim.small
                            easing.type: Easing.Linear
                        }
                    }
                }

                MouseArea {
                    id: monitor1MouseArea
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor

                    onClicked: {
                        root.closeRequested();
                        monitor1ToggleProcess.running = true;
                    }

                    onEntered: root.selectedButtonIndex = 0
                }
            }

            // Monitor 2 button
            Rectangle {
                width: 50
                height: 50
                radius: Appearance.rounding.small
                color: root.selectedButtonIndex === 1 ? NixConfig.primary : NixConfig.surfaceContainer
                scale: monitor2MouseArea.containsMouse || root.selectedButtonIndex === 1 ? 1.1 : 1.0
                transformOrigin: Item.Center

                Behavior on color {
                    ColorAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.Linear
                    }
                }

                Behavior on scale {
                    NumberAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.OutBack
                    }
                }

                Text {
                    anchors.centerIn: parent
                    text: root.monitor2On ? "󰎧" : "󰎩"
                    font.family: Appearance.font.mono
                    font.pixelSize: Appearance.font.large
                    font.bold: true
                    color: root.selectedButtonIndex === 1 ? NixConfig.textOnPrimary : NixConfig.primary

                    Behavior on color {
                        ColorAnimation {
                            duration: Appearance.anim.small
                            easing.type: Easing.Linear
                        }
                    }
                }

                MouseArea {
                    id: monitor2MouseArea
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor

                    onClicked: {
                        root.closeRequested();
                        monitor2ToggleProcess.running = true;
                    }

                    onEntered: root.selectedButtonIndex = 1
                }
            }
        }

        // Divider
        Rectangle {
    width: Math.max(buttonRow.width, monitorRow.width, calendar.width) + Appearance.padding.large * 2
            height: 1
            color: NixConfig.outline
            opacity: 0.3
        }

        // Power buttons row
        Row {
            id: buttonRow
            anchors.horizontalCenter: parent.horizontalCenter
            spacing: Appearance.spacing.normal

            // Power off button
            Rectangle {
                width: 50
                height: 50
                radius: Appearance.rounding.small
                color: root.selectedButtonIndex === 2 ? NixConfig.primary : NixConfig.surfaceContainer
                scale: powerMouseArea.containsMouse || root.selectedButtonIndex === 2 ? 1.1 : 1.0
                transformOrigin: Item.Center

                Behavior on color {
                    ColorAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.Linear
                    }
                }

                Behavior on scale {
                    NumberAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.OutBack
                    }
                }

                Text {
                    anchors.centerIn: parent
                    text: "󰐥"
                    font.family: Appearance.font.mono
                    font.pixelSize: Appearance.font.large
                    color: root.selectedButtonIndex === 2 ? NixConfig.textOnPrimary : NixConfig.primary

                    Behavior on color {
                        ColorAnimation {
                            duration: Appearance.anim.small
                            easing.type: Easing.Linear
                        }
                    }
                }

                MouseArea {
                    id: powerMouseArea
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor

                    onClicked: {
                        root.closeRequested();
                        powerProcess.running = true;
                    }

                    onEntered: root.selectedButtonIndex = 2
                }
            }

            // Restart button
            Rectangle {
                width: 50
                height: 50
                radius: Appearance.rounding.small
                color: root.selectedButtonIndex === 3 ? NixConfig.primary : NixConfig.surfaceContainer
                scale: restartMouseArea.containsMouse || root.selectedButtonIndex === 3 ? 1.1 : 1.0
                transformOrigin: Item.Center

                Behavior on color {
                    ColorAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.Linear
                    }
                }

                Behavior on scale {
                    NumberAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.OutBack
                    }
                }

                Text {
                    anchors.centerIn: parent
                    text: "󰜉"
                    font.family: Appearance.font.mono
                    font.pixelSize: Appearance.font.large
                    color: root.selectedButtonIndex === 3 ? NixConfig.textOnPrimary : NixConfig.primary

                    Behavior on color {
                        ColorAnimation {
                            duration: Appearance.anim.small
                            easing.type: Easing.Linear
                        }
                    }
                }

                MouseArea {
                    id: restartMouseArea
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor

                    onClicked: {
                        root.closeRequested();
                        restartProcess.running = true;
                    }

                    onEntered: root.selectedButtonIndex = 3
                }
            }

            // Logout button
            Rectangle {
                width: 50
                height: 50
                radius: Appearance.rounding.small
                color: root.selectedButtonIndex === 4 ? NixConfig.primary : NixConfig.surfaceContainer
                scale: logoutMouseArea.containsMouse || root.selectedButtonIndex === 4 ? 1.1 : 1.0
                transformOrigin: Item.Center

                Behavior on color {
                    ColorAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.Linear
                    }
                }

                Behavior on scale {
                    NumberAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.OutBack
                    }
                }

                Text {
                    anchors.centerIn: parent
                    text: "󰍃"
                    font.family: Appearance.font.mono
                    font.pixelSize: Appearance.font.large
                    color: root.selectedButtonIndex === 4 ? NixConfig.textOnPrimary : NixConfig.primary

                    Behavior on color {
                        ColorAnimation {
                            duration: Appearance.anim.small
                            easing.type: Easing.Linear
                        }
                    }
                }

                MouseArea {
                    id: logoutMouseArea
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor

                    onClicked: {
                        root.closeRequested();
                        logoutProcess.running = true;
                    }

                    onEntered: root.selectedButtonIndex = 4
                }
            }

            // Suspend button
            Rectangle {
                width: 50
                height: 50
                radius: Appearance.rounding.small
                color: root.selectedButtonIndex === 5 ? NixConfig.primary : NixConfig.surfaceContainer
                scale: suspendMouseArea.containsMouse || root.selectedButtonIndex === 5 ? 1.1 : 1.0
                transformOrigin: Item.Center

                Behavior on color {
                    ColorAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.Linear
                    }
                }

                Behavior on scale {
                    NumberAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.OutBack
                    }
                }

                Text {
                    anchors.centerIn: parent
                    text: "󰒲"
                    font.family: Appearance.font.mono
                    font.pixelSize: Appearance.font.large
                    color: root.selectedButtonIndex === 5 ? NixConfig.textOnPrimary : NixConfig.primary

                    Behavior on color {
                        ColorAnimation {
                            duration: Appearance.anim.small
                            easing.type: Easing.Linear
                        }
                    }
                }

                MouseArea {
                    id: suspendMouseArea
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor

                    onClicked: {
                        root.closeRequested();
                        suspendProcess.running = true;
                    }

                    onEntered: root.selectedButtonIndex = 5
                }
            }

            // Lock button
            Rectangle {
                width: 50
                height: 50
                radius: Appearance.rounding.small
                color: root.selectedButtonIndex === 6 ? NixConfig.primary : NixConfig.surfaceContainer
                scale: lockMouseArea.containsMouse || root.selectedButtonIndex === 6 ? 1.1 : 1.0
                transformOrigin: Item.Center

                Behavior on color {
                    ColorAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.Linear
                    }
                }

                Behavior on scale {
                    NumberAnimation {
                        duration: Appearance.anim.small
                        easing.type: Easing.OutBack
                    }
                }

                Text {
                    anchors.centerIn: parent
                    text: ""
                    font.family: Appearance.font.mono
                    font.pixelSize: Appearance.font.large
                    font.bold: true
                    color: root.selectedButtonIndex === 6 ? NixConfig.textOnPrimary : NixConfig.primary

                    Behavior on color {
                        ColorAnimation {
                            duration: Appearance.anim.small
                            easing.type: Easing.Linear
                        }
                    }
                }

                MouseArea {
                    id: lockMouseArea
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor

                    onClicked: {
                        root.closeRequested();
                        lockTimer.start();
                    }

                    onEntered: root.selectedButtonIndex = 6
                }
            }
        }
    }
}
