pragma ComponentBehavior: Bound

import "../../config"
import "../../services"
import "../shared"
import Quickshell
import Quickshell.Wayland
import Quickshell.Hyprland
import QtQuick
import QtQuick.Layouts

// Creates bar windows for each screen
Variants {
    id: variants
    // Filter to specific monitor by name (run: hyprctl monitors -j | jq -r '.[].name' to see all)
    // Bar monitor is configured in nix-config.json (generated by Nix)
    model: Quickshell.screens.filter(screen => screen.name === NixConfig.barMonitor)

    // Function to toggle menu on primary screen
    function toggleMenu() {
        // Toggle on the first scope (primary screen)
        if (variants.instances.length > 0) {
            const firstScope = variants.instances[0];
            firstScope.menuOpen = !firstScope.menuOpen;
            firstScope.bar.menuOpen = firstScope.menuOpen;
        }
    }

    // Function to close menu on primary screen
    function closeMenu() {
        if (variants.instances.length > 0) {
            const firstScope = variants.instances[0];
            firstScope.menuOpen = false;
            firstScope.bar.menuOpen = false;
        }
    }

    Scope {
        id: scope

        required property ShellScreen modelData
        property bool menuOpen: false
        property bool menuMouseInside: false
        property alias bar: bar

        PanelWindow {
            id: window

            // Bar configuration
            readonly property int barWidth: 64
            readonly property int contentWidth: barWidth + 4

            // Visibility state
            property bool isHovered: false

            screen: scope.modelData
            color: "transparent"

            // Layer shell configuration
            anchors {
                top: true
                bottom: true
                right: true
            }

            // The exclusive zone reserves space on the right edge
            exclusiveZone: contentWidth
            implicitWidth: contentWidth

            WlrLayershell.namespace: "nick-bar"
            WlrLayershell.layer: WlrLayer.Top

            // Animate width changes
            Behavior on implicitWidth {
                Anim {
                    duration: Appearance.anim.normal
                    easing.bezierCurve: Appearance.anim.expressiveDefaultSpatial
                }
            }

            // Background
            Rectangle {
                id: background

                anchors.fill: parent
                color: NixConfig.layer(NixConfig.background, 0)
                radius: 0
                border.width: 1
                border.color: Qt.alpha(NixConfig.outline, 0.2)
            }

            // Bar content
            Bar {
                id: bar

                anchors.fill: parent

                onOpenMenuRequested: {
                    scope.menuOpen = true;
                    bar.menuOpen = true;
                }
            }

            // Hover detection for auto-hide (future feature) and tray popout
            MouseArea {
                anchors.fill: parent
                hoverEnabled: true
                acceptedButtons: Qt.LeftButton | Qt.RightButton
                propagateComposedEvents: true

                onEntered: window.isHovered = true
                onExited: {
                    window.isHovered = false;
                    clearTrayTimer.restart();
                    clearVolumeTimer.restart();
                    bar.clearNixButtonHover();
                    if (scope.menuOpen) {
                        clearMenuTimer.restart();
                    }
                }

                onPositionChanged: mouse => {
                    let prevTrayIdx = bar.hoveredTrayIndex;
                    let trayIdx = bar.calculateTrayIndex(mouse.y);
                    let overTray = trayIdx >= 0;
                    let volumeY = bar.volumeWidget.y;
                    let volumeHeight = bar.volumeWidget.height;
                    let overVolume = mouse.y >= volumeY && mouse.y <= volumeY + volumeHeight;

                    // Update hover states (this will open popouts if hovering)
                    bar.updateTrayHover(mouse.y);
                    bar.updateVolumeHover(mouse.y);
                    bar.updateNixButtonHover(mouse.y, scope.menuOpen);

                    // Tray timer logic: start timer if tray popout is open but mouse not over tray/popout
                    if (trayPopout.visible) {
                        if (overTray || trayPopout.mouseInside) {
                            clearTrayTimer.stop();
                            // If we switched to a different tray icon, the content already updated above
                        } else if (!clearTrayTimer.running) {
                            clearTrayTimer.start();
                        }
                    }

                    // Volume timer logic: start timer if volume popout is open but mouse not over volume/popout
                    if (volumePopout.visible) {
                        if (overVolume || volumePopout.mouseInside) {
                            clearVolumeTimer.stop();
                        } else if (!clearVolumeTimer.running) {
                            clearVolumeTimer.start();
                        }
                    }

                    // Menu close logic: start timer if menu is open but mouse not over button/menu
                    if (scope.menuOpen) {
                        if (bar.nixButtonHovered || scope.menuMouseInside) {
                            clearMenuTimer.stop();
                        } else if (!clearMenuTimer.running) {
                            clearMenuTimer.start();
                        }
                    }
                }

                onClicked: mouse => {
                    // Only handle clicks in the tray area
                    let idx = bar.calculateTrayIndex(mouse.y);
                    if (idx >= 0) {
                        bar.handleTrayClick(mouse.y, mouse.button);
                    } else {
                        // Let click propagate to underlying elements (like Nix button)
                        mouse.accepted = false;
                    }
                }

                onWheel: wheel => {
                    // Don't handle wheel events, let them propagate to underlying components (like Volume)
                    wheel.accepted = false;
                }
            }

            // Timer for tray popout clear delay
            Timer {
                id: clearTrayTimer
                interval: 150
                onTriggered: {
                    // Only clear if mouse not in popout
                    if (!trayPopout.mouseInside) {
                        bar.clearTrayHover();
                    }
                }
            }

            // Timer for volume popout clear delay
            Timer {
                id: clearVolumeTimer
                interval: 150
                onTriggered: {
                    // Only clear if mouse not in popout
                    if (!volumePopout.mouseInside) {
                        bar.clearVolumeHover();
                    }
                }
            }

            // Timer for menu close delay
            Timer {
                id: clearMenuTimer
                interval: 150
                onTriggered: {
                    // Close menu if mouse not over button and not over menu
                    if (!bar.nixButtonHovered && !scope.menuMouseInside) {
                        scope.menuOpen = false;
                        bar.menuOpen = false;
                    }
                }
            }
        }

        // Menu popup window
        PanelWindow {
            id: menuWindow

            screen: scope.modelData
            color: "transparent"

            anchors {
                right: true
                bottom: true
                top: true
            }

            margins {
                right: window.contentWidth
                bottom: 20
                top: 20
            }

            implicitWidth: menu.width
            implicitHeight: menu.height

            // Stay visible during animation
            visible: scope.menuOpen || menu.x > -menu.width

            WlrLayershell.namespace: "nick-menu"
            WlrLayershell.layer: WlrLayer.Overlay
            WlrLayershell.exclusionMode: ExclusionMode.Ignore

            // Use Hyprland focus grab to ensure keyboard input is captured
            HyprlandFocusGrab {
                active: scope.menuOpen
                windows: [menuWindow]
            }

            BarMenu {
                id: menu

                anchors.bottom: parent.bottom
                // Animate x position for slide effect (account for right extension)
                x: scope.menuOpen ? 0 : menu.width

                Behavior on x {
                    Anim {
                        duration: Appearance.anim.normal
                        easing.type: Easing.OutCubic  // Smooth deceleration without overshoot
                    }
                }

                open: scope.menuOpen
                onCloseRequested: {
                    scope.menuOpen = false;
                    bar.menuOpen = false;
                }

                // Track hover on the menu itself
                HoverHandler {
                    onHoveredChanged: {
                        scope.menuMouseInside = hovered;
                        if (hovered) {
                            clearMenuTimer.stop();
                        } else {
                            clearMenuTimer.restart();
                        }
                    }
                }
            }
        }

        // Single tray popout instance
        BarTrayPopout {
            id: trayPopout
            screen: scope.modelData
            trayItem: bar.hoveredTrayItem
            targetIconCenterY: bar.trayIconCenterY
            barRef: bar

            // When mouse leaves popout, start clear timer
            onMouseInsideChanged: {
                if (!mouseInside && visible) {
                    clearTrayTimer.restart();
                } else {
                    clearTrayTimer.stop();
                }
            }
        }

        BarVolumePopout {
            id: volumePopout
            screen: scope.modelData
            targetIconCenterY: bar.volumeIconCenterY
            barMouseInside: bar.volumeHovered

            // When mouse leaves popout, start clear timer
            onMouseInsideChanged: {
                if (!mouseInside && visible) {
                    clearVolumeTimer.restart();
                } else {
                    clearVolumeTimer.stop();
                }
            }
        }
    }
}
