#!/usr/bin/env bash

# Source plugin submodules
source ~/.config/zsh/plugins/vim/vim.plugin.zsh
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme
source ~/.config/zsh/plugins/powerlevel10k/config/p10k-robbyrussell.zsh
source ~/.config/zsh/.p10k.zsh

autoload -U compinit && compinit

# history setup
setopt APPEND_HISTORY
setopt SHARE_HISTORY
HISTFILE=$HOME/.zsh_history
SAVEHIST=1000
HISTSIZE=999
setopt HIST_EXPIRE_DUPS_FIRST
setopt EXTENDED_HISTORY

# Start typing + [Up-Arrow] - fuzzy find history forward
autoload -U up-line-or-beginning-search
zle -N up-line-or-beginning-search
bindkey '\e[A' up-line-or-beginning-search
# Start typing + [Down-Arrow] - fuzzy find history backward
autoload -U down-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '\e[B' down-line-or-beginning-search

addToPathFront() {
  if [[ "$PATH" != *"$1"* ]]; then
    export PATH=$1:$PATH
  fi
}
addToPathFront $HOME/bin:/usr/local/bin
addToPathFront $HOME/.local/bin
addToPathFront $HOME/.yarn/bin
addToPathFront $HOME/.config/yarn/global/node_modules/.bin
addToPathFront $HOME/.cargo/bin
addToPathFront $HOME/go/bin

export VISUAL=nvim
export EDITOR="$VISUAL"

export CLICOLOR=1
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'

bindkey -s '^ ' "^utmux_sessionizer.sh\n"
bindkey -s -M vicmd '^ ' "ddAtmux_sessionizer.sh\n"
bindkey -s ^f "^uvim_opener.sh\n"
bindkey -s -M vicmd ^f "ddAvim_opener.sh\n"
bindkey -s ^b "^ubtop\n"
bindkey -s -M vicmd ^b "ddAbtop\n"
bindkey -s ^v "^uvi\n"
bindkey -s -M vicmd ^v "ddAvi\n"
bindkey -s ^y "^uy\n"
bindkey -s -M vicmd ^y "ddAy\n"
bindkey -s ^g "^ulazygit\n"
bindkey -s -M vicmd ^g "ddAlazygit\n"

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
eval "$(zoxide init zsh)"

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

